const nodemailer = require('nodemailer');
const fs = require('fs');
const path = require('path');

class EmailService {
  constructor() {
    this.transporter = null;
    this.settings = {
      host: '',
      port: 587,
      secure: false,
      auth: {
        user: '',
        pass: ''
      },
      from: '',
      to: '',
      enabled: false
    };
    this.loadSettings();
  }

  loadSettings() {
    const settingsPath = path.join(__dirname, '../email-settings.json');
    try {
      if (fs.existsSync(settingsPath)) {
        const data = fs.readFileSync(settingsPath, 'utf8');
        this.settings = { ...this.settings, ...JSON.parse(data) };
      }
    } catch (error) {
      console.error('Error loading email settings:', error);
    }
  }

  saveSettings(settings) {
    const settingsPath = path.join(__dirname, '../email-settings.json');
    this.settings = { ...this.settings, ...settings };
    try {
      fs.writeFileSync(settingsPath, JSON.stringify(this.settings, null, 2));
      this.initializeTransporter();
      return true;
    } catch (error) {
      console.error('Error saving email settings:', error);
      return false;
    }
  }

  initializeTransporter() {
    if (!this.settings.host || !this.settings.auth.user || !this.settings.auth.pass) {
      return;
    }

    this.transporter = nodemailer.createTransporter({
      host: this.settings.host,
      port: this.settings.port,
      secure: this.settings.secure,
      auth: {
        user: this.settings.auth.user,
        pass: this.settings.auth.pass
      }
    });
  }

  async testConnection() {
    if (!this.transporter) {
      this.initializeTransporter();
    }
    
    if (!this.transporter) {
      throw new Error('Email configuration not set up');
    }

    try {
      await this.transporter.verify();
      return { success: true };
    } catch (error) {
      return { success: false, error: error.message };
    }
  }

  async sendDailyReport(reportData, attachmentPath = null) {
    if (!this.settings.enabled || !this.transporter) {
      return { success: false, error: 'Email service not configured or disabled' };
    }

    const today = new Date().toLocaleDateString();
    const subject = `Daily Sales Report - ${today}`;
    
    let html = `
      <h2>Daily Sales Report - ${today}</h2>
      <div style="font-family: Arial, sans-serif;">
        <h3>Summary</h3>
        <table style="border-collapse: collapse; width: 100%; margin-bottom: 20px;">
          <tr style="background-color: #f2f2f2;">
            <td style="border: 1px solid #ddd; padding: 8px; font-weight: bold;">Total Sales</td>
            <td style="border: 1px solid #ddd; padding: 8px;">₹${reportData.totalAmount.toFixed(2)}</td>
          </tr>
          <tr>
            <td style="border: 1px solid #ddd; padding: 8px; font-weight: bold;">Total Transactions</td>
            <td style="border: 1px solid #ddd; padding: 8px;">${reportData.totalTransactions}</td>
          </tr>
          <tr style="background-color: #f2f2f2;">
            <td style="border: 1px solid #ddd; padding: 8px; font-weight: bold;">Table Sales</td>
            <td style="border: 1px solid #ddd; padding: 8px;">${reportData.tableSales}</td>
          </tr>
          <tr>
            <td style="border: 1px solid #ddd; padding: 8px; font-weight: bold;">Parcel Sales</td>
            <td style="border: 1px solid #ddd; padding: 8px;">${reportData.parcelSales}</td>
          </tr>
        </table>
    `;

    if (reportData.topItems && reportData.topItems.length > 0) {
      html += `
        <h3>Top Selling Items</h3>
        <table style="border-collapse: collapse; width: 100%; margin-bottom: 20px;">
          <tr style="background-color: #f2f2f2;">
            <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">Item</th>
            <th style="border: 1px solid #ddd; padding: 8px; text-align: right;">Quantity Sold</th>
            <th style="border: 1px solid #ddd; padding: 8px; text-align: right;">Revenue</th>
          </tr>
      `;
      
      reportData.topItems.forEach((item, index) => {
        html += `
          <tr ${index % 2 === 0 ? 'style="background-color: #f9f9f9;"' : ''}>
            <td style="border: 1px solid #ddd; padding: 8px;">${item.name}</td>
            <td style="border: 1px solid #ddd; padding: 8px; text-align: right;">${item.quantity}</td>
            <td style="border: 1px solid #ddd; padding: 8px; text-align: right;">₹${item.revenue.toFixed(2)}</td>
          </tr>
        `;
      });
      
      html += `</table>`;
    }

    html += `
        <p style="color: #666; font-size: 12px; margin-top: 30px;">
          This is an automated report generated by your POS system.
        </p>
      </div>
    `;

    const mailOptions = {
      from: this.settings.from,
      to: this.settings.to,
      subject: subject,
      html: html,
      attachments: attachmentPath ? [{ path: attachmentPath }] : []
    };

    try {
      await this.transporter.sendMail(mailOptions);
      return { success: true };
    } catch (error) {
      return { success: false, error: error.message };
    }
  }

  getSettings() {
    return { ...this.settings, auth: { ...this.settings.auth, pass: '***' } };
  }
}

module.exports = EmailService;
